config/routes.rb
Rails.application.routes.draw do
  root "pages#index"
  get "history", to: "pages#history"
  get "tourism", to: "pages#tourism"
  get "contacts", to: "pages#contacts"
  get "askmanaoag", to: "pages#askmanaoag"
  get "checkparking", to: "pages#checkparking"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
  def history
  end

  def tourism
  end

  def contacts
  end

  def askmanaoag
  end

  def checkparking
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Explore" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="container mx-auto mt-28 px-5 flex">
      <header class="navbar">
        <div class="logo-container">
          <%= image_tag "manaoag-seal.png", alt: "Manaoag Logo", class: "w-24 h-auto mx-auto" %>
          <div class="logo-text">
            <h1>Municipality of Manaoag</h1>
            <p>Province of Pangasinan</p>
          </div>
        </div>

        <div class="nav-buttons">
          <div class="dropdown">
            <button class="officials-btn">Barangay Officials ▼</button>
            <div class="dropdown-content">
              <%= link_to "Tourism", tourism_path %>
              <%= link_to "Check Parking", checkparking_path %>
              <%= link_to "History", history_path %>
            </div>
          </div>
          <button class="things-btn">Things to Do</button>
          <button class="things-btn">Useful Links</button>
        </div>
      </header>
      <%= yield %>
    </main>
    <footer>
      2025 All Rights Reserved.
    </footer>
  </body>
</html>

app/views/pages/askmanaoag.html.erb
<div>
  <h1 class="font-bold text-4xl">Pages#askmanaoag</h1>
  <p>Find me in app/views/pages/askmanaoag.html.erb</p>
</div>

app/views/pages/contacts.html.erb
<div>
  <h1 class="font-bold text-4xl">Pages#contacts</h1>
  <p>Find me in app/views/pages/contacts.html.erb</p>
</div>

app/views/pages/history.html.erb
<div>
  <h1 class="font-bold text-4xl">Pages#history</h1>
  <p>Find me in app/views/pages/history.html.erb</p>
  <%= image_tag "old-manaoag.webp", alt: "Image of old manaoag", class: "w-30 h-auto mx-auto" %>
  <p>
  The four-century old Municipality of Manaoag was formerly called “Sapang”. During the occupancy of the Agustinians, and important religious event occurred that pilgrimage became the etymological beginning of what is now called the Municipality of Manaoag.
  </p>
  <p>
Manaoag derived from a miraculous name sighting of the Blessed Virgin Mary carrying the infant of Jesus in her arms. Its history began with an account of a farmer walking home after tilling the land. The farmer, tired, but with a heart wholly submitted to the Lord, saw a blinding bright light and heard a woman with a sweet voice calling to him from the woody place above the Baloking Creek.  He turned his head toward the direction from where he had heard the voice and saw the image of the Virgin and her son in rich and brilliant attires standing on the branch of a Molave tree.  After long moments, during which the man stood numb and speechless, he knelt down as the Lady continued in her singularly sweet voice: “Son, I want a church here in my honor”. It could be surmised that such joy from that extraordinary experience would not remain locked for long in the heart of the man, but would overflow to others.
  </p>
  <p>

Words from this apparition inevitably spread to nearby places and to the rest of the province.  The Image of the Virgin Mary was brought to the Philippines from Mexico in 1605 by the Dominicans and a church was constructed where it is said the Virgin wanted her shrine erected.
  </p>
  <p>

The name, “Manaoag” with ‘ma”, meaning “to”, prefixed to “taoag”, meaning “to call”, is given to the place where the apparition of the Virgin Mary occurred.  The Our Lady of Manaoag is thus known as “The Virgin Mary Who Calls”.
  </p>
  <p>

At the turn of the century, a religious couple from Manila came to Lingayen to take up permanent residency.  In their pilgrimage to the Virgin, they found her church in poor condition and resolved to spend a part of their fortune in building a better church.  They presented their proposal to the Dominican authorities in Manaoag and, upon acceptance the construction of the new church was started in the year 1701.  It was a permanent structure of brick and hardwood and was considered at the time an architectural achievement.  The inauguration of the church took place when the miraculous image of the Virgin of the Holy Rosary of Manaoag was fittingly enthroned in her new shrine.  This account appears in the book of records of the Dominican Order in the Province of Pangasinan.
  </p>
  <p>
On June 26, 1898, during the struggle of the Filipinos for Philippine Independence, the image of the Holy Virgin of the Rosary was transported to Dagupan for safekeeping.  It was the first time in three hundred years that the Holy Image left its sanctuary in Manaoag.  The Image was returned to Manaoag on April 21, 1926, an event that will stay etched forever in the religious history of the province.  Tens of thousands of Catholics devotes swarmed the Public Square and the churchyard where the Virgin of the Holy Rosay was solemnly crowned as the Patron Saint of the Province of Pangasinan.
  </p>
  <p>
Trek to the shrine of Nuestra Senora de Manaoag or the Lady Who Calls has never waned over the years.  The town has become the Mecca for devout Catholics with thousands of pilgrims from all walks of life visiting the Holy Shrine all year round.
  </p>
  <p>
The presence of the miraculous Image of the Virgin of the Holy Rosary hastened the development and the consequent progress of the Municipality of Manaoag as people from all parts of the province and other provinces flocked to pay homage to Her.
  </p>
  <p>

  </p>
  <p>
The Municipality of Manaoag progressed rapidly and, in 1642, it became a regular “pueblo” or town under the Spanish Colonial Government.  The first “CAPITAN” was Don G. Finuliar, a civic leader of Manaoag.  The Local Government operated under the encomienda system, although a decree prohibiting the enforcement of this type of System was issued by the King of Spain in 1574.  And despite efforts by the governor to implement the king’s order, the system continued for the purpose of tax collection until it was abolished a century later.

  </p>
  <p>
For administration purposes, the Municipality of Manaoag was divided into barangays ruled or administered by chief or a Cabeza de Barangay.  The Municipal administration was under the “Tribunal” headed by the “Capitan del Pueblo and composed of five (5) delegates with the power to deliberate on matters of administration although the parish had the power to decide on all matters that concerned the town’s internal affairs. In other words, the parish priest had the power to initiate and approve any or all ordinances passed by the “Tribunal”.  The Royal Decree of 1893, otherwise known as the Maura Law, provided for reforms in the Local Government, although the changes were never carried out in view of the outbreak of the Philippine Revolution three (3) years after. The Maura Law provided a certain amount of autonomy in the local government but was too late to forestall the general discontent that surrounded the Spanish colonial system and which led thereafter to the Philippine Revolution of 1896.

  </p>
  <p>

The policy of attraction to the town was started during the American period.  Public schools were established.  The first teachers were American soldiers who used English as a medium of instruction.  These American soldiers were supervised by Reverend W.D. Mc-Kinnon, United States Army Chaplain.  The first civilian American supervising teacher was Mr. Shehan, who waged house-to-house campaign to enroll pupils in the schools and appointed Manaoag residents as teachers.
  </p>
  <p>
The population of Manaoag in 1990 was 16,793.  The Poblacion was the most densely populated and the people built their houses mostly along the roads.  Today, Manaoag contains up to 72,191 people and is still considered a religious center for the devout Catholics in the Philippines.
  </p>
</div>

app/views/pages/index.html.erb
It works!

app/views/pages/tourism.html.erb
<div>
  <h1 class="font-bold text-4xl">Pages#tourism</h1>
  <p>Find me in app/views/pages/tourism.html.erb</p>
</div>